/*
 * touch-gestures.h
 *
 *  Created on: Apr 23, 2020
 *      Author: murugan
 */

#ifndef TOUCH_GESTURES_H_
#define TOUCH_GESTURES_H_

/**
 * Event type for Touch Screen Gestures
 */
enum touch_gestures_event_type {
      /* marks the begining of Touch Gesture events. Not used except for validation */
      TOUCH_GESTURE_EVENT_NONE = 0x800,

	  //Tap
      TOUCH_GESTURE_EVENT_1FINGER_TAP,
      TOUCH_GESTURE_EVENT_2FINGER_TAP,

	  //Swipe
      TOUCH_GESTURE_EVENT_1FINGER_SWIPE_UP,
      TOUCH_GESTURE_EVENT_1FINGER_SWIPE_DOWN,
      TOUCH_GESTURE_EVENT_1FINGER_SWIPE_LEFT,
      TOUCH_GESTURE_EVENT_1FINGER_SWIPE_RIGHT,

      TOUCH_GESTURE_EVENT_2FINGER_SWIPE_UP,
      TOUCH_GESTURE_EVENT_2FINGER_SWIPE_DOWN,
      TOUCH_GESTURE_EVENT_2FINGER_SWIPE_LEFT,
      TOUCH_GESTURE_EVENT_2FINGER_SWIPE_RIGHT,

      TOUCH_GESTURE_EVENT_3FINGER_SWIPE_UP,
      TOUCH_GESTURE_EVENT_3FINGER_SWIPE_DOWN,
      TOUCH_GESTURE_EVENT_3FINGER_SWIPE_LEFT,
      TOUCH_GESTURE_EVENT_3FINGER_SWIPE_RIGHT,

      TOUCH_GESTURE_EVENT_4FINGER_SWIPE_UP,
      TOUCH_GESTURE_EVENT_4FINGER_SWIPE_DOWN,
      TOUCH_GESTURE_EVENT_4FINGER_SWIPE_LEFT,
      TOUCH_GESTURE_EVENT_4FINGER_SWIPE_RIGHT,

	  //Pinch
	  TOUCH_GESTURE_EVENT_2FINGER_PINCH_IN,
      TOUCH_GESTURE_EVENT_2FINGER_PINCH_OUT,

	  TOUCH_GESTURE_EVENT_3FINGER_PINCH_IN,
      TOUCH_GESTURE_EVENT_3FINGER_PINCH_OUT,

	  //Rotate
      TOUCH_GESTURE_EVENT_2FINGER_ROTATE_CLOCKWISE,
      TOUCH_GESTURE_EVENT_2FINGER_ROTATE_ANTICLOCKWISE,

	  TOUCH_GESTURE_EVENT_3FINGER_ROTATE_CLOCKWISE,
      TOUCH_GESTURE_EVENT_3FINGER_ROTATE_ANTICLOCKWISE,

	  TOUCH_GESTURE_EVENT_4FINGER_ROTATE_CLOCKWISE,
      TOUCH_GESTURE_EVENT_4FINGER_ROTATE_ANTICLOCKWISE,


      TOUCH_GESTURE_EVENT_END /* marks the end of Touch Gesture events */
};

int touch_gestures_init (void);
int touch_gestures_exit (void);

enum touch_gestures_event_type touch_gestures_get(void);

int touch_gestures_get_finger_count(void);

int touch_gestures_set_touch_device(const char* sysname);


#endif /* TOUCH_GESTURES_H_ */
